/* 0ba3d143f76ae7b7d0da65118b7d3a2de273a283
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type DemoQueryQueryVariables = Types.Exact<{
  datasource: Types.Scalars['String']['input'];
  contextItem: Types.Scalars['String']['input'];
  language: Types.Scalars['String']['input'];
}>;
export type DemoQueryQuery = {
  __typename?: 'Query';
  datasource?: {
    __typename?: 'App';
    id: string;
    name: string;
  } | {
    __typename?: 'AppRoute';
    id: string;
    name: string;
  } | {
    __typename?: 'BYOCRenderingParameters';
    id: string;
    name: string;
  } | {
    __typename?: 'C__Route';
    id: string;
    name: string;
  } | {
    __typename?: 'C__StandardTemplate';
    id: string;
    name: string;
  } | {
    __typename?: 'Card';
    id: string;
    name: string;
  } | {
    __typename?: 'ContentBanner';
    id: string;
    name: string;
  } | {
    __typename?: 'ContentBlock';
    id: string;
    name: string;
  } | {
    __typename?: 'FEaaSRenderingParameters';
    id: string;
    name: string;
  } | {
    __typename?: 'ImageSettings';
    id: string;
    name: string;
  } | {
    __typename?: 'JSSLayout';
    id: string;
    name: string;
  } | {
    __typename?: 'JavaScriptRendering';
    id: string;
    name: string;
  } | {
    __typename?: 'JsonRendering';
    id: string;
    name: string;
  } | {
    __typename?: 'MainMenu';
    id: string;
    name: string;
  } | {
    __typename?: 'MainMenuItem';
    id: string;
    name: string;
  } | {
    __typename?: 'MenuItem';
    id: string;
    name: string;
  } | {
    __typename?: 'NavigationHeader';
    id: string;
    name: string;
  } | {
    __typename?: 'RenderEngineType';
    id: string;
    name: string;
  } | {
    __typename?: 'SubMenuGroup';
    id: string;
    name: string;
  } | {
    __typename?: 'SubMenuHeadingOrSpace';
    id: string;
    name: string;
  } | {
    __typename?: 'SubMenuItem';
    id: string;
    name: string;
  } | {
    __typename?: 'SvgIconsMediaFolder';
    id: string;
    name: string;
  } | {
    __typename?: 'TopMenu';
    id: string;
    name: string;
  } | {
    __typename?: 'TopMenuItem';
    id: string;
    name: string;
  } | {
    __typename?: 'UnknownItem';
    id: string;
    name: string;
  } | null;
};
export declare const DemoQueryDocument: DocumentNode<DemoQueryQuery, Types.Exact<{
  datasource: Types.Scalars['String']['input'];
  contextItem: Types.Scalars['String']['input'];
  language: Types.Scalars['String']['input'];
}>>;